/** Columns needed for `PropertyCard` / listing grids (excludes heavy text like description). */
export const PROPERTY_CARD_LIST_SELECT = `
  id,
  title,
  slug,
  rent_per_week,
  room_type,
  images,
  bedrooms,
  bathrooms,
  furnished,
  bond,
  lease_length,
  listing_type,
  featured,
  address,
  suburb,
  state,
  postcode,
  latitude,
  longitude,
  landlord_id,
  university_id,
  campus_id,
  available_from,
  available_to,
  status,
  max_occupants,
  couple_surcharge_per_week,
  parking_surcharge_per_week,
  parking_available,
  created_at,
  landlord_profiles ( id, full_name, avatar_url, verified ),
  universities ( id, name, slug ),
  campuses ( id, name, slug )
`
