-- Landlord read access for student_profiles is defined in:
--   **landlord_read_student_profiles_definer.sql**
-- (SECURITY DEFINER helper so nested bookings RLS does not hide rows from the dashboard.)
--
-- Run `landlord_read_student_profiles_definer.sql` once per Supabase project.
-- This file is kept so older docs that mention this filename still point you to the right place.
