/**
 * AcroForm /T names on docs/qld/form18a-renamed.pdf.
 * Generated from docs/qld/qld-form18a-corrected-field-map.json (133 data fields).
 * Regenerate: node scripts/generate-qld-form18a-renamed-fields.mjs
 */

export const QLD_FORM18A_ACTION_BUTTONS = ['Reset form', 'Print form'] as const

export const QLD_FORM18A_RENAMED_FIELDS = {
  Lessor_name_trading_name: 'Lessor name/trading name',
  Lessor_address: 'Lessor address',
  Lessor_postcode: 'Lessor postcode',
  Lessor_address2: 'Lessor address2',
  Lessor_ABN_optional1: 'Lessor ABN (optional)1',
  Lessor_phone_number: 'Lessor phone number',
  Lessor_mobile_number: 'Lessor mobile number',
  Lessor_email_address: 'Lessor email address',
  Tenant1_full_name_s: 'Tenant 1 full name/s',
  Tenant1_phone_number: 'Tenant 1 phone number',
  Tenant1_email: 'Tenant 1 email',
  Emengency_contact_full_name_s1: 'Emengency contact full name/s1',
  Emengency_contact_phone1: 'Emengency contact phone1',
  Emengency_contact_email1: 'Emengency contact email1',
  Tenant2_full_name_s: 'Tenant 2 full name/s',
  Tenant2_phone_number: 'Tenant 2 phone number',
  Tenant2_email: 'Tenant 2 email',
  Emengency_contact_full_name_s2: 'Emengency contact full name/s2',
  Emengency_contact_phone2: 'Emengency contact phone2',
  Emengency_contact_email2: 'Emengency contact email2',
  Tenant3_full_name_s: 'Tenant 3 full name/s',
  Tenant3_email: 'Tenant 3 email',
  Tenant3_phone_number: 'Tenant 3 phone number',
  Emengency_contact_full_name_s3: 'Emengency contact full name/s3',
  Emengency_contact_phone3: 'Emengency contact phone3',
  Emengency_contact_email3: 'Emengency contact email3',
  Lessor_s_agent_full_name_trading_name: 'Lessor\'s agent full name/trading name',
  Lessor_s_agent_address_line1: 'Lessor\'s agent address line 1',
  Lessor_s_agent_postcode: 'Lessor\'s agent postcode',
  Lessor_s_agent_address_line2: 'Lessor\'s agent address line 2',
  Lessor_s_agent_ABN_optional1: 'Lessor\'s agent ABN (optional)1',
  Lessor_s_agent_phone_number: 'Lessor\'s agent phone number',
  Lessor_s_agent_mobile_number: 'Lessor\'s agent mobile number',
  Lessor_s_agent_email: 'Lessor\'s agent email',
  Lessors_email: 'Lessors email',
  notice_lessor_email_no: 'notice_lessor_email_no',
  notice_lessor_email_yes: 'notice_lessor_email_yes',
  Lessor_mobile_number_for_text_messages: 'Lessor mobile number for text messages',
  Lessor_facsimilie_number: 'Lessor facsimilie number',
  notice_lessor_fax_no: 'notice_lessor_fax_no',
  notice_lessor_fax_yes: 'notice_lessor_fax_yes',
  notice_lessor_text_yes: 'notice_lessor_text_yes',
  notice_lessor_text_no: 'notice_lessor_text_no',
  Tenant_s_email: 'Tenant/s email',
  notice_tenant_email_no: 'notice_tenant_email_no',
  notice_tenant_email_yes: 'notice_tenant_email_yes',
  Tenant_s_mobile_number_for_text_messages: 'Tenant/s mobile number for text messages',
  Tenant_s_facsimilie_number: 'Tenant/s facsimilie number',
  notice_tenant_text_yes: 'notice_tenant_text_yes',
  notice_tenant_text_no: 'notice_tenant_text_no',
  notice_tenant_fax_no: 'notice_tenant_fax_no',
  notice_tenant_fax_yes: 'notice_tenant_fax_yes',
  Agents_email: 'Agents email',
  notice_agent_email_no: 'notice_agent_email_no',
  notice_agent_email_yes: 'notice_agent_email_yes',
  Agent_mobile_number_for_text_messages: 'Agent mobile number for text messages',
  Agent_facsimilie_number: 'Agent facsimilie number',
  notice_agent_fax_no: 'notice_agent_fax_no',
  notice_agent_text_yes: 'notice_agent_text_yes',
  notice_agent_text_no: 'notice_agent_text_no',
  notice_agent_fax_yes: 'notice_agent_fax_yes',
  Address_of_the_rental_premises1: 'Address of the rental premises1',
  Address_of_the_rental_premises2: 'Address of the rental premises2',
  Postcode: 'Postcode',
  Inclusions_provided1: 'Inclusions provided1',
  Details_of_current_repair_orders_for_the_rental_premises_or_inclusions2: 'Details of current repair orders for the rental premises or inclusions2',
  term_fixed: 'term_fixed',
  term_periodic: 'term_periodic',
  End_date_dd_mm_yyyy: 'End date (dd/mm/yyyy)',
  Start_date_dd_mm_yyyy: 'Start date (dd/mm/yyyy)',
  Rent_amount: 'Rent amount',
  rent_period_monthly: 'rent_period_monthly',
  rent_period_fortnightly: 'rent_period_fortnightly',
  rent_period_weekly: 'rent_period_weekly',
  Day_the_rent_must_be_paid_on: 'Day the rent must be paid on',
  week_fortnight_or_month: 'week, fortnight or month',
  Method1: 'Method 1',
  Method2: 'Method 2',
  BSB_number: 'BSB number',
  Bank_building_society_credit_union: 'Bank/building society/credit union',
  Account_number: 'Account number',
  Account_name: 'Account name',
  Payment_reference: 'Payment reference',
  Place_of_rent_payment: 'Place of rent payment',
  Day_of_last_rent_increase_dd_mm_yyyy: 'Day of last rent increase (dd/mm/yyyy)',
  Rental_bond_amount: 'Rental bond amount',
  services_other_yes: 'services_other_yes',
  services_other_no: 'services_other_no',
  services_electricity_no: 'services_electricity_no',
  services_electricity_yes: 'services_electricity_yes',
  Type_of_services_the_tenant_must_pay_for: 'Type of services the tenant must pay for',
  services_gas_no: 'services_gas_no',
  services_gas_yes: 'services_gas_yes',
  services_phone_no: 'services_phone_no',
  services_phone_yes: 'services_phone_yes',
  water_charge_no: 'water_charge_no',
  water_charge_yes: 'water_charge_yes',
  Cost_for_other_services: 'Cost for other services',
  Cost_for_electricity: 'Cost for electricity',
  Cost_for_gas: 'Cost for gas',
  Cost_for_phone: 'Cost for phone',
  How_electricity_must_be_paid_for: 'How electricity must be paid for',
  How_gas_must_be_paid_for: 'How gas must be paid for',
  How_phone_must_be_paid_for: 'How phone must be paid for',
  How_other_services_must_be_paid_for: 'How other services must be paid for',
  Number_of_persons_allowed_to_reside_at_the_premises: 'Number of persons allowed to reside at the premises',
  bylaws_applicable_no: 'bylaws_applicable_no',
  bylaws_applicable_yes: 'bylaws_applicable_yes',
  bylaws_copy_given_yes: 'bylaws_copy_given_yes',
  bylaws_copy_given_no: 'bylaws_copy_given_no',
  Phone_number2: 'Phone number2',
  Nominated_electrical_repairer: 'Nominated electrical repairer',
  Phone_number3: 'Phone number3',
  Nominated_plumbing_repairer: 'Nominated plumbing repairer',
  Phone_number4: 'Phone number4',
  Nominated_other_repairer: 'Nominated other repairer',
  repairers_first_contact_yes: 'repairers_first_contact_yes',
  repairers_first_contact_no: 'repairers_first_contact_no',
  Name: 'Name',
  Phone_number5: 'Phone number5',
  Number_of_the_approved_pets1: 'Number of the approved pets1',
  Type_of_pets_approved2: 'Type of pets approved_2',
  Number_of_the_approved_pets2: 'Number of the approved pets2',
  Type_of_pets_approved1: 'Type of pets approved_1',
  Special_terms: 'Special terms',
  Lessor_agent_name_trading_name: 'Lessor/agent name/trading name',
  Name_of_tenant1: 'Name of tenant 1',
  Date_of_signature_dd_mm_yyyy2: 'Date of signature (dd/mm/yyyy)2',
  Date_of_signature_dd_mm_yyyy1: 'Date of signature (dd/mm/yyyy)1',
  Name_of_tenant3: 'Name of tenant 3',
  Name_of_tenant2: 'Name of tenant 2',
  Date_of_signature_dd_mm_yyyy4: 'Date of signature (dd/mm/yyyy)4',
  Date_of_signature_dd_mm_yyyy3: 'Date of signature (dd/mm/yyyy)3',
} as const

export type QldForm18aRenamedFieldName = (typeof QLD_FORM18A_RENAMED_FIELDS)[keyof typeof QLD_FORM18A_RENAMED_FIELDS]
