import type { QldFormR18FillProps } from './officialQldFormR18Fill.js'
import { formatQldFormR18PaymentReference } from './qldFormR18PaymentReference.js'

export function qldFormR18SampleFillProps(): QldFormR18FillProps {
  return {
    providerName: 'Quang Dinh',
    providerStreet: '10 Provider Street',
    providerSuburbLine: 'Jamboree Heights QLD',
    providerPostcode: '4074',
    providerPhone: '0400111222',
    providerMobile: '0400111222',
    providerEmail: 'quang.provider@example.com',
    providerAbn: '',
    residentFullName: 'Robert Resident',
    residentPhone: '0411222333',
    residentEmail: 'robert.resident@example.com',
    emergencyContactName: 'Pat Example',
    emergencyContactPhone: '0499888777',
    emergencyContactEmail: 'pat.example@example.com',
    premisesStreet: '22 Rental Street',
    premisesSuburbLine: 'Jamboree Heights QLD',
    premisesPostcode: '4074',
    roomNumber: '1',
    inclusions: 'Room: 1; Furnished; linen supplied',
    studentAccommodation: false,
    termFixed: true,
    startDateIso: '2026-10-01',
    endDateIso: '2027-09-30',
    weeklyRent: 250,
    bondAmount: 1000,
    rentDueWeekday: 'Thursday',
    method1: 'Direct credit',
    method2: 'Cash. Cost to resident: None. Financial benefit to provider: None.',
    bankName: 'Example Bank',
    accountName: 'Quang Dinh',
    bsb: '123456',
    accountNumber: '98765432',
    paymentReference: formatQldFormR18PaymentReference({
      fullName: 'Robert Resident',
      lastName: 'Resident',
      roomNumber: '1',
    }),
    lastRentIncreaseIso: null,
    utilitiesLine: '',
    personsInRoom: 1,
    personsAtPremises: 4,
    houseRulesProvided: true,
    providerNoticeEmail: { permitted: true, address: 'quang.provider@example.com' },
    providerNoticeSms: { permitted: false, address: '' },
    residentNoticeEmail: { permitted: true, address: 'robert.resident@example.com' },
    residentNoticeSms: { permitted: false, address: '' },
  }
}
