/**
 * AcroForm /T names on docs/qld/form-r18-v15.pdf (RTA Form R18 v15 Sep25).
 * Names are the official field titles, including RTA typos (Emengency, facsimilie).
 */
export const QLD_FORM_R18_ACTION_BUTTONS = ['Reset form', 'Print form'] as const

export const QLD_FORM_R18_FIELDS = {
  Provider_name: 'Agent or manager/provider name/trading name',
  Provider_address_1: 'Address1',
  Provider_address_2: 'Address2',
  Provider_postcode: 'Postcode2',
  Provider_phone: 'Phone number1',
  Provider_mobile: 'Mobile number1',
  Provider_email: 'Email1',
  Provider_abn: 'ABN (optional)1',
  Resident1_full_name: 'Resident 1 full name/s',
  Resident1_phone: 'Phone number2',
  Resident1_email: 'Email2',
  Resident1_emergency_name: 'Emengency contact full name/s1',
  Resident1_emergency_phone: 'Emengency contact phone1',
  Resident1_emergency_email: 'Emengency contact email1',
  Resident2_full_name: 'Resident 2 full name/s',
  Resident2_phone: 'Phone number3',
  Resident2_email: 'Email3',
  Resident2_emergency_name: 'Emengency contact full name/s2',
  Resident2_emergency_phone: 'Emengency contact phone2',
  Resident2_emergency_email: 'Emengency contact email2',
  Agent_name: "Manager/provider’s agent name/trading name2",
  Agent_address_1: 'Address3',
  Agent_address_2: 'Address4',
  Agent_postcode: 'Postcode3',
  Agent_phone: 'Phone number4',
  Agent_mobile: 'Mobile number2',
  Agent_email: 'Email4',
  Agent_abn: "Manager/provider's agent ABN (optional)2",
  Representative_name: 'Resident’s representative for notices name/trading name3',
  Representative_address_1: 'Address5',
  Representative_address_2: 'Address6',
  Representative_postcode: 'Postcode4',
  Representative_phone: 'Phone number5',
  Representative_mobile: 'Mobile number3',
  Representative_email: 'Email5',
  Notice_provider_email: 'Agent or manager/provider email',
  Notice_provider_sms: 'Agent or manager/provider mobile number for text messages',
  Notice_provider_fax: 'Agent or manager/provider facsimilie number',
  Notice_resident_email: 'Resident/s email',
  Notice_resident_sms: 'Resident/s mobile number for text messages',
  Notice_resident_fax: 'Resident/s facsimilie number',
  Notice_agent_email: "Provider's agent email",
  Notice_agent_sms: "Provider's agent mobile number for text messages",
  Notice_agent_fax: "Provider's agent facsimilie number",
  Notice_representative_email: 'Resident’s representative email',
  Notice_representative_sms: 'Resident’s representative mobile number for text messages',
  Notice_representative_fax: 'Resident’s representative facsimilie number',
  Room_number: 'Room number',
  Premises_address_1: 'Rental premises address 1',
  Premises_address_2: 'Rental premises address 2',
  Premises_postcode: 'Postcode1',
  Inclusions: 'Inclusions provided',
  Start_date: 'Start date (dd/mm/yyyy)1',
  End_date: 'End date (dd/mm/yyyy)',
  Rent_amount: 'Rent amount',
  Accommodation: 'Accommodation',
  Food_service: 'Food service',
  Personal_care_service: 'Personal care service',
  Other_services_1: 'Other services line 1',
  Other_services_2: 'Other services line 2',
  Other_services_3: 'Other services line 3',
  Other_services_provided: 'Other services to be provided',
  Rent_due_day: 'Day the rent must be paid on',
  Rent_due_period: 'Insert weekly, fortnightly or monthly',
  Method_1: 'Method 1',
  Method_2: 'Method 2',
  Bank_name: 'Bank/building society/credit union',
  Account_name: 'Account name',
  Account_number: 'Account number',
  Bsb: 'BSB number',
  Payment_reference: 'Payment reference',
  Place_of_payment: 'Place of rent payment',
  Last_rent_increase: 'The day the rent was last increased for the room (dd/mm/yyyy)',
  Rent_increase_how: 'How will the rent increase be calculated?',
  Rent_increase_start: 'Start date (dd/mm/yyyy)2',
  Bond_amount: 'Rental bond amount',
  Utilities: 'Utility services for which the resident must pay',
  Persons_in_room: 'Number of persons allowed to reside in the room',
  Persons_at_premises: 'Number of persons allowed to reside at the rental premises',
  Pets_type_1: 'Type of pets approved_1',
  Pets_number_1: 'Number3',
  Pets_type_2: 'Type of pets approved_2',
  Pets_number_2: 'Number4',
  Special_terms: 'Special terms',
  Sign_provider_name: 'Agent, manager/provider or provider’s agent name/trading name',
  Sign_resident_1_name: 'Name of resident 1',
  Sign_resident_2_name: 'Name of resident 2',
  Sign_date_1: 'Date of signature (dd/mm/yyyy)1',
  Sign_date_2: 'Date of signature (dd/mm/yyyy)2',
  Sign_date_3: 'Date of signature (dd/mm/yyyy)3',
} as const

export const QLD_FORM_R18_CHECKS = {
  term_fixed: 'Fixed term agreement',
  term_periodic: 'Periodic agreement',
  rent_weekly: 'Weekly',
  rent_fortnightly: 'Fortnightly',
  rent_monthly: 'Monthly',
  level_1: 'Level 1',
  level_2: 'Level 2',
  level_3: 'Level 3',
  student_accommodation: 'Student accommodation',
  item15_level_1: 'Level 1a',
  item15_level_2: 'Level 2a',
  item15_level_3: 'Level 3a',
  breakfast: 'Breakfast',
  lunch: 'Lunch',
  dinner: 'Dinner',
  notice_provider_email_yes: 'Yes1',
  notice_provider_email_no: 'No1',
  notice_provider_sms_yes: 'Yes1a',
  notice_provider_sms_no: 'No1a',
  notice_provider_fax_yes: 'Yes2',
  notice_provider_fax_no: 'No2',
  notice_resident_email_yes: 'Yes3',
  notice_resident_email_no: 'No3',
  notice_resident_sms_yes: 'Yes3a',
  notice_resident_sms_no: 'No3a',
  notice_resident_fax_yes: 'Yes4',
  notice_resident_fax_no: 'No4',
  notice_agent_email_yes: 'Yes5',
  notice_agent_email_no: 'No6',
  notice_agent_sms_yes: 'Yes7',
  notice_agent_sms_no: 'No7',
  notice_agent_fax_yes: 'Yes8',
  notice_agent_fax_no: 'No8',
  notice_representative_email_yes: 'Yes9',
  notice_representative_email_no: 'No9',
  notice_representative_sms_yes: 'Yes10',
  notice_representative_sms_no: 'No10',
  notice_representative_fax_yes: 'Yes11',
  notice_representative_fax_no: 'No11',
  rent_can_increase_yes: 'Yes12',
  rent_can_increase_no: 'No12',
  house_rules_given_yes: 'Yes13',
  house_rules_given_no: 'No13',
  bylaws_applicable_yes: 'Yes14',
  bylaws_applicable_no: 'No14',
  bylaws_copy_yes: 'Yes15',
  bylaws_copy_no: 'No15',
} as const
