/**
 * Living Console backdrop.
 *
 * Per HANDOFF.md non-goal 6 this is the **single** non-flat surface allowed
 * across admin. Three layers:
 *
 * 1. Static aerial-suburb SVG (`/admin/aerial-backdrop.svg`) — generated by
 *    `scripts/build-aerial-backdrop.mjs`. Lives in `/public` so it's cached
 *    independently of the JS bundle and ships zero KB of inline geometry.
 * 2. Cream radial wash (top-left) — keeps the hero copy area legible.
 * 3. Coral + navy radial washes — warmth top-right, depth bottom-left.
 *
 * To tweak the aerial, edit the generator script and re-run it; the SVG asset
 * is committed but treated as a build artefact for source-of-truth purposes.
 */
export function HomeBackdrop() {
  return (
    <div aria-hidden className="pointer-events-none absolute inset-0 z-0 overflow-hidden">
      <img
        src="/admin/aerial-backdrop.svg"
        alt=""
        decoding="async"
        loading="eager"
        className="absolute inset-0 h-full w-full object-cover"
        style={{ opacity: 0.32 }}
      />
      <div
        className="absolute"
        style={{
          inset: '-20% -10% 40% -10%',
          background:
            'radial-gradient(ellipse 70% 50% at 20% 0%, rgba(254,249,228,.55), rgba(254,249,228,0) 70%)',
        }}
      />
      <div
        className="absolute"
        style={{
          top: '-12%',
          right: '-8%',
          width: 520,
          height: 520,
          borderRadius: '50%',
          background: 'radial-gradient(circle, rgba(255,111,97,.06), rgba(255,111,97,0) 65%)',
        }}
      />
      <div
        className="absolute"
        style={{
          bottom: '-10%',
          left: '-6%',
          width: 640,
          height: 640,
          borderRadius: '50%',
          background: 'radial-gradient(circle, rgba(31,42,68,.04), rgba(31,42,68,0) 65%)',
        }}
      />
    </div>
  )
}
